import Head from 'next/head'
import {Inter} from 'next/font/google'
import {Wizard} from "@/components/Wizard";
const inter = Inter({subsets: ['latin']})

export default function Home() {
    return (
        <>
            <Head>
                <title>App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
            </Head>
            <div>
                <div>
                    <h1>Add aria</h1>
                    <button>X</button>
                </div>
                <Wizard tilte={"sdasds"}/>
            </div>
        </>
    )
}
